version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sample_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d myapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: postgres_data

networks:
  myapp-network:
    name: myapp-network
    external: true
